The contents of the updated `.github/workflows/main.yml` file will depend on the specific issue causing the failure. Without the error logs, I cannot provide the exact modifications needed. However, I will ensure that the workflow file is properly configured and includes all required steps and dependencies.

Please provide the error logs so that I can analyze the issue and make the necessary modifications to the workflow file.
